name: 'Pyright Analysis Action'
description: 'Generate a visualisation of your Python project type completeness'
author: 'Martijn Pieters'

branding:
  icon: 'table'
  color: 'green'

inputs:
  report:
    description: >
      Path to the Pyright verifytypes report. Must be in JSON format, so
      produced with the `--outputjson` flag.
    required: true
  div_id:
    description: >
      Provide a value for the `id` attribute on the `<div>` tag that wraps the
      report in the generated HTML page. If omitted, a random UUID is used.
  template:
    description: >
      A string template for the final HTML page. The template must contain the
      string `{{ graph }}`, which will be replaced with a `<div>` HTML element
      containing the generated graph. Whitespace following the `{{` opening
      braces and preceding the  `}}` closing braces is optional, any number of
      Unicode whitespace characters are accepted, so `{{graph}}` is equivalent
      to `{{   \n graph \t  }}`. This option is mutually exclusive with
      `template_file`.
  template_file:
    description: >
      Pathname to a file containing the template for the final HTML page. The
      template must contain the string `{{ graph }}`, which will be replaced
      with a `<div>` HTML element containing the generated graph. Whitespace
      following the `{{` opening braces and preceding the  `}}` closing braces
      is optional, any number of Unicode whitespace characters are accepted, so
      `{{graph}}` is equivalent to `{{   \n graph \t  }}`. This option is
      mutually exclusive with `template`.
  comment_on_pr:
    description: >
      If set to `true` (or `yes`, or `1`, `t` or `y`), and the current workflow
      run was triggered by a `pull_request` or `workflow_run` event indirectly
      triggered by a `pull_request`, then a comment will be added to that pull
      request. If there already is a comment posted by this action then the
      existing comment is updated instead. Requires a github token with either
      `issues: write` or `pull-requests: write` permission. Note that a
      `pull_request` workflow running in a forked repo will only get a read-only
      token so you'll need to put this action in a `workflow_run` workflow
      instead. See the action documentation for details.
    default: "false"
  github_token:
    description: >
      The github token to use when posting a comment on a PR. Defaults to the
      `GITHUB_TOKEN` secret for this workflow job.
    default: ${{ github.token }}


outputs:
  html_url:
    description:
      The URL of the interactive graph.
  preview_url:
    description:
      The URL of the preview image (SVG).
  expiration:
    description:
      ISO8601-formatted date time value for when the published page expires.
  

runs:
  using: docker
  image: docker://ghcr.io/mjpieters/pyright-analysis-action:v0.2.0@sha256:5ba754217671dd08bb37c827193c5a64186f3195dfff401c633c23ac7892aa07
