name: Type Completeness graph

on:
  pull_request:

permissions:
  contents: read

env:
  PROJECT_NAME: 'prefect'

jobs:
  generate_graph:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Install uv
      uses: astral-sh/setup-uv@v5.1.0

    - name: Generate report JSON
      run: |
        # Generate the type completeness report for your Python project.
        # This assumes your Python project can be installed as editable
        # from files in the current directory
        uv tool run --with "$PROJECT_NAME" pyright \
          --ignoreexternal --outputjson \
          --verifytypes $PROJECT_NAME > type_completeness_report.json || true

    - name: Generate report visualisation
      uses: mjpieters/pyright-analysis-action@v0.1.1
      env:
        # Smokeshow authorisation key for your project. Optional, but recommended.
        # See documentation for how to get one.
        SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}
      with:
          report: type_completeness_report.json
